Task/readme docker
friendica/docker pull request #145
Opened 2021-01-05 18:11 UTC by nupplaphil

Fixes #144

2021-01-05 18:26 UTC, MrPetovan requested changes

2021-01-05 18:26 UTC, MrPetovan commented on README-MAINTENANCE.md
> +Never ever change a file/folder inside a directory without a `.` a t the beginning (`2018.05-rc`, ...).
```suggestion
Never ever change a file/folder inside a directory without a `.` at the beginning (`2018.05-rc`, ...).
```

2021-01-05 18:26 UTC, MrPetovan commented on README-MAINTENANCE.md
> +Therefore, the script uses the official docker github action tool [`bashbrew`](https://github.com/docker-library/bashbrew.git) to transform the repository version structure into github action command
```suggestion
The script uses the official docker GitHub Action tool [`bashbrew`](https://github.com/docker-library/bashbrew.git) to transform the repository version structure into GitHub Action commands.
```

2021-01-05 18:26 UTC, MrPetovan commented on README-MAINTENANCE.md
> +This script automatically creates autotests actions based on the docker image version structure and variants.
```suggestion
This script automatically creates autotests actions based on the Docker image version structure and variants.
```

2021-01-05 18:26 UTC, MrPetovan commented on README-MAINTENANCE.md
> +GitHub Actions helps to automate tasks for Continuous Integration (= autotest docker images) and Continuous Deployment (= autocreate docker images based on the friendica upstream).
```suggestion
GitHub Actions helps to automate tasks for Continuous Integration (= autotest Docker images) and Continuous Deployment (= autocreate Docker images based on the friendica upstream).
```

2021-01-05 18:26 UTC, MrPetovan commented on README-MAINTENANCE.md
> +The official docker image is available at https://hub.docker.com/_/friendica.
```suggestion
The official Docker image is available at https://hub.docker.com/_/friendica.
```

2021-01-05 18:26 UTC, MrPetovan commented on README-MAINTENANCE.md
> +Any other versions lower than this won't be available from the official docker hub anymore.
```suggestion
It contains the minimum supported version, which will automatically be available as a Docker image.
Any other versions lower than this won't be available from the official Docker Hub anymore.
```

2021-01-05 18:26 UTC, MrPetovan commented on README-MAINTENANCE.md
>  This "manifest" is used to create a new PR in the official-images [repository](https://github.com/docker-library/official-images/) for deploying the changes to the docker hub.
```suggestion
This "manifest" is used to create a new PR in the official-images [repository](https://github.com/docker-library/official-images/) for deploying the changes to the Docker Hub.
```

2021-01-05 18:26 UTC, MrPetovan commented on README-MAINTENANCE.md
> +It maps additional tags onto docker image versions.
```suggestion
It maps additional tags onto Docker image versions.
```

2021-01-05 18:26 UTC, MrPetovan commented on generate-stackbrew-library.sh
> +  [stable]='2021.01'
Can't we have this in a `stable.txt` file like the `latest` and `develop` in the same file? Or can't we just use the `latest`?

2021-01-05 19:21 UTC, MrPetovan approved these changes

2021-01-05 19:23 UTC, MrPetovan commented
The GitHub Action Stackbrew manifest step failed: https://github.com/friendica/docker/pull/145/checks?check_run_id=1652102214

2021-01-05 19:27 UTC, nupplaphil commented
I removed it again .. I'll better create a additional PR for it ;-)
=> will remove the need of a local docker/bashbrew environment

2021-01-05 19:33 UTC, merged

2021-01-06 07:26 UTC, valvin1 commented
thank you :) my instance is now with 2021.01 version