set /etc/msmtprc 'auth' parameter from SMTP_AUTH env
friendica/docker pull request #150
Opened 2021-04-14 04:10 UTC by miklobit

In some cases smtp config parameter  'auth login' instead 'auth on' is needed to avoid msmtp errors.

2021-04-14 06:54 UTC, nupplaphil requested changes
Thank you for your work!
Looks good to me.

One more thing:
Please add the new environment variable here https://github.com/friendica/docker/blob/stable/README.md#mail-settings

2021-04-14 22:31 UTC, MrPetovan approved these changes

2021-04-14 22:32 UTC, MrPetovan requested changes

2021-04-14 22:32 UTC, MrPetovan commented on README.md
> +- `SMTP_AUTH` Auth mode for the SMTP Mail-Gateway. (Default: `On`)
Code standards: The indentation should be 1 tab.

2021-04-17 11:17 UTC, nupplaphil commented
@miklobit - I fixed the indentation for you :-)

2021-04-17 11:17 UTC, nupplaphil approved these changes

2021-04-18 04:15 UTC, MrPetovan approved these changes

2021-04-18 04:15 UTC, merged