Preserve local config during update
friendica/docker pull request #172
Opened 2021-10-06 03:24 UTC by elrido

During the last update from 2021.07 to 2021.09 my [local.config.php got replaced](https://github.com/friendica/docker/issues/166#issuecomment-934713008). I found that the archive that gets downloaded from https://files.friendi.ca/ contained such file, while it is not present in the friendica git tree.

This change will exclude that file from the configuration file update. It also amends a path used in the installation to point to the unpacked archive.

Is it correct to only change this in the template scripts in the top level or should this also get changed in the scripts for each of the docker images (i.e. `2021.09/apache/entrypoint.sh`)? I'm not sure on the process/script to refresh these.

2021-10-06 06:37 UTC, nupplaphil commented
Please execute `./update.sh` after changing the template and commit every changed file as well :) 

But I think this PR fixes not the root cause.. I think I have to recreate the stable archive again @tobiasd :( what do you say? In the meantime I'll add this change to have a running image again

2021-10-06 15:20 UTC, MrPetovan requested changes

2021-10-06 15:20 UTC, MrPetovan commented on docker-entrypoint.sh
> +    rsync $rsync_options --update --exclude=/local.config.php /usr/src/friendica/config/ /var/www/html/config/
This needs to exclude `addon.config.php` as well.

2021-10-06 16:51 UTC, tobiasd commented
@nupplaphil can you regenerate the release archive plus the sig and the sum files?

2021-10-06 19:58 UTC, elrido commented on docker-entrypoint.sh
> +    rsync $rsync_options --update --exclude=/local.config.php /usr/src/friendica/config/ /var/www/html/config/
Thank you, added it.

2021-10-06 19:59 UTC, elrido commented
Thank you all for the guidance. Did apply the change to all the images via update.sh as well.

2021-10-06 20:02 UTC, MrPetovan approved these changes
Looks good to me, @nupplaphil ?

2021-10-07 17:49 UTC, merged

2021-10-07 17:49 UTC, nupplaphil commented
merged, but I'll recreate the archive without the config as well to fix the root cause..